name: Build/release

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  build:
    if: github.ref_type == 'branch'
    runs-on: macos-15

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build GUI
        run: npm run build:gui

  release:
    if: github.ref_type == 'tag'
    runs-on: macos-15

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
