name: Build/release

on: push

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.x
      - run: npm ci
      - run: GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run build
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            fri3d-badge-fixer-linux-x86_64-1.0.0.AppImage
            fri3d-badge-fixer-mac-arm64-1.0.0.dmg
            fri3d-badge-fixer-mac-x64-1.0.0.dmg
            fri3d-badge-fixer-win-x64-1.0.0.zip
            LICENSE
